### ISSUE TITLE
Doesn’t work in yuzu

### ISSUE THREAD

**Issue by anirudhb** [hjmmc/WebGyroForCemuhook#16]
I believe this is a problem with your udp server implementation since it works with ds4. See yuzu-emu/yuzu#3817.

**Comment by kongomongo** [comment]
What exactly do you think the reason is?

Are these compatible with Yuzu and if yes whats the difference?

https://github.com/hjmmc/WebGyroForCemuhook/blob/master/app.js
https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/DS4Control/UdpServer.cs

**Comment by kongomongo** [comment]
Not sure I understand closing the issue? Is it resolved?

**Comment by WitSyrup** [comment]
在yuzu和ryujinx中不起作用，是因为没有加速度数据现在有人在原项目上新增此功能来支持yuzu和ryujinx了，可以下载腾讯QQ加入群组：201271279（掌机体感粉丝群）来下载此项目。
It does not work in yuzu and ryujinx because there is no acceleration data. Now someone has added this function to the original project to support yuzu and ryujinx. You can download Tencent QQ to join the group: 201271279 (handheld sensor fan group) to download this project .
